# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.define "docker" do |v|
    v.vm.hostname = "packer-docker"
    v.vm.box = "ubuntu/trusty64"
    v.vm.synced_folder ".", "/home/vagrant/packer"
    v.vm.provision "docker"

    v.vm.provision "shell" do |s|
      s.path = "scripts/packer_base.sh"
      s.args = [
        ENV['DOCKER_LOGIN_EMAIL'],
        ENV['DOCKER_USER_NAME'],
        ENV['DOCKER_PASSWORD'],
        ENV['DOCKER_LOGIN_SERVER'],
        ""
      ]
    end
  end
end
